SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
GO
IF DB_ID('LostFoundDB') IS NULL CREATE DATABASE LostFoundDB;
GO
USE LostFoundDB;
GO
CREATE TABLE lf_roles (role_id INT IDENTITY PRIMARY KEY, role_name NVARCHAR(20) NOT NULL UNIQUE);
CREATE TABLE lf_users (user_id INT IDENTITY PRIMARY KEY, first_name NVARCHAR(80) NOT NULL, last_name NVARCHAR(80) NOT NULL, email NVARCHAR(255) NOT NULL UNIQUE, password_hash NVARCHAR(255) NOT NULL, role_id INT NOT NULL REFERENCES lf_roles(role_id), status NVARCHAR(20) NOT NULL DEFAULT 'Active', created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), updated_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
CREATE TABLE lf_categories (category_id INT IDENTITY PRIMARY KEY, name NVARCHAR(100) NOT NULL UNIQUE, description NVARCHAR(500), status NVARCHAR(20) NOT NULL DEFAULT 'Active');
CREATE TABLE lf_locations (location_id INT IDENTITY PRIMARY KEY, name NVARCHAR(150) NOT NULL UNIQUE, description NVARCHAR(500), status NVARCHAR(20) NOT NULL DEFAULT 'Active');
CREATE TABLE lf_lost_items (lost_item_id INT IDENTITY PRIMARY KEY, readable_id AS ('L-'+CONVERT(VARCHAR(4),YEAR(created_at))+'-'+RIGHT('0000'+CONVERT(VARCHAR(8),lost_item_id),4)) PERSISTED, user_id INT NOT NULL REFERENCES lf_users(user_id), item_name NVARCHAR(180) NOT NULL, category_id INT NOT NULL REFERENCES lf_categories(category_id), color NVARCHAR(80), brand NVARCHAR(100), lost_location_id INT NOT NULL REFERENCES lf_locations(location_id), lost_date DATETIME2 NOT NULL, description NVARCHAR(1500) NOT NULL, private_details NVARCHAR(2000), status NVARCHAR(40) NOT NULL DEFAULT 'Open', created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), updated_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
CREATE TABLE lf_found_items (found_item_id INT IDENTITY PRIMARY KEY, readable_id AS ('F-'+CONVERT(VARCHAR(4),YEAR(created_at))+'-'+RIGHT('0000'+CONVERT(VARCHAR(8),found_item_id),4)) PERSISTED, reported_by_user_id INT NOT NULL REFERENCES lf_users(user_id), item_name NVARCHAR(180) NOT NULL, category_id INT NOT NULL REFERENCES lf_categories(category_id), color NVARCHAR(80), brand NVARCHAR(100), found_location_id INT NOT NULL REFERENCES lf_locations(location_id), found_date DATETIME2 NOT NULL, description NVARCHAR(1500) NOT NULL, private_details NVARCHAR(2000), custody_status NVARCHAR(40) NOT NULL DEFAULT 'In Custody', status NVARCHAR(40) NOT NULL DEFAULT 'Unclaimed', created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), updated_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
CREATE TABLE lf_item_images (image_id INT IDENTITY PRIMARY KEY, item_type NVARCHAR(10) NOT NULL CHECK (item_type IN ('lost','found')), item_id INT NOT NULL, image_path NVARCHAR(500) NOT NULL, original_filename NVARCHAR(255), created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
CREATE TABLE lf_matches (match_id INT IDENTITY PRIMARY KEY, lost_item_id INT NOT NULL REFERENCES lf_lost_items(lost_item_id), found_item_id INT NOT NULL REFERENCES lf_found_items(found_item_id), match_score INT NOT NULL, category_score INT NOT NULL, color_score INT NOT NULL, location_score INT NOT NULL, date_score INT NOT NULL, brand_score INT NOT NULL, keyword_score INT NOT NULL, status NVARCHAR(30) NOT NULL DEFAULT 'Pending', created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), CONSTRAINT uq_lf_match UNIQUE(lost_item_id, found_item_id));
CREATE TABLE lf_claims (claim_id INT IDENTITY PRIMARY KEY, readable_id AS ('C-'+CONVERT(VARCHAR(4),YEAR(submitted_at))+'-'+RIGHT('0000'+CONVERT(VARCHAR(8),claim_id),4)) PERSISTED, found_item_id INT NOT NULL REFERENCES lf_found_items(found_item_id), claimant_user_id INT NOT NULL REFERENCES lf_users(user_id), status NVARCHAR(30) NOT NULL DEFAULT 'Pending', submitted_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), reviewed_by_user_id INT NULL REFERENCES lf_users(user_id), reviewed_at DATETIME2 NULL, rejection_reason NVARCHAR(1000));
CREATE TABLE lf_claim_verification (verification_id INT IDENTITY PRIMARY KEY, claim_id INT NOT NULL REFERENCES lf_claims(claim_id), question NVARCHAR(500) NOT NULL, claimant_answer NVARCHAR(1500) NOT NULL, staff_notes NVARCHAR(1500), is_verified BIT NOT NULL DEFAULT 0);
CREATE TABLE lf_activity_logs (log_id INT IDENTITY PRIMARY KEY, user_id INT REFERENCES lf_users(user_id), action NVARCHAR(100) NOT NULL, entity_type NVARCHAR(50), entity_id INT, details NVARCHAR(MAX), created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
CREATE INDEX ix_found_status_date ON lf_found_items(status, found_date DESC);
CREATE INDEX ix_lost_status_date ON lf_lost_items(status, lost_date DESC);
CREATE INDEX ix_claim_status ON lf_claims(status, submitted_at DESC);
GO
