import bcrypt from 'bcrypt';
import { DemoStore } from './demoStore.js';
import { getPool, sql } from '../config/database.js';
import { buildMatches } from './matchingService.js';

const itemMap = (row, type) => ({ id: row.id, readableId: row.readableId, [type === 'found' ? 'reporterId' : 'userId']: row.ownerId, name: row.name, category: row.category, color: row.color, brand: row.brand, location: row.location, date: row.date, description: row.description, privateDetails: row.privateDetails, ...(type === 'found' ? { custodyStatus: row.custodyStatus } : {}), status: row.status, image: row.image, createdAt: row.createdAt, updatedAt: row.updatedAt });
const bind = (request, values) => { Object.entries(values).forEach(([name, value]) => request.input(name, value ?? null)); return request; };

export class SqlStore extends DemoStore {
  async init() {
    this.pool = await getPool();
    const [users, categories, locations, found, lost, matches, claims, verification, logs] = await Promise.all([
      this.pool.request().query(`SELECT u.user_id id,u.first_name firstName,u.last_name lastName,u.email,u.password_hash passwordHash,r.role_name role,u.status,u.created_at createdAt FROM lf_users u JOIN lf_roles r ON r.role_id=u.role_id`),
      this.pool.request().query(`SELECT category_id id,name,description,status FROM lf_categories`),
      this.pool.request().query(`SELECT location_id id,name,description,status FROM lf_locations`),
      this.pool.request().query(`SELECT f.found_item_id id,f.readable_id readableId,f.reported_by_user_id ownerId,f.item_name name,c.name category,f.color,f.brand,l.name location,f.found_date date,f.description,f.private_details privateDetails,f.custody_status custodyStatus,f.status,(SELECT TOP 1 image_path FROM lf_item_images WHERE item_type='found' AND item_id=f.found_item_id ORDER BY image_id) image,f.created_at createdAt,f.updated_at updatedAt FROM lf_found_items f JOIN lf_categories c ON c.category_id=f.category_id JOIN lf_locations l ON l.location_id=f.found_location_id`),
      this.pool.request().query(`SELECT i.lost_item_id id,i.readable_id readableId,i.user_id ownerId,i.item_name name,c.name category,i.color,i.brand,l.name location,i.lost_date date,i.description,i.private_details privateDetails,i.status,(SELECT TOP 1 image_path FROM lf_item_images WHERE item_type='lost' AND item_id=i.lost_item_id ORDER BY image_id) image,i.created_at createdAt,i.updated_at updatedAt FROM lf_lost_items i JOIN lf_categories c ON c.category_id=i.category_id JOIN lf_locations l ON l.location_id=i.lost_location_id`),
      this.pool.request().query(`SELECT match_id dbId,CONCAT(lost_item_id,'-',found_item_id) id,lost_item_id lostItemId,found_item_id foundItemId,match_score score,category_score category,color_score color,location_score location,date_score date,brand_score brand,keyword_score keyword,status,created_at createdAt FROM lf_matches`),
      this.pool.request().query(`SELECT claim_id id,readable_id readableId,found_item_id foundItemId,claimant_user_id claimantUserId,status,submitted_at submittedAt,reviewed_by_user_id reviewerId,reviewed_at reviewedAt,rejection_reason rejectionReason FROM lf_claims`),
      this.pool.request().query(`SELECT claim_id claimId,question,claimant_answer answer,staff_notes staffNotes,is_verified isVerified FROM lf_claim_verification`),
      this.pool.request().query(`SELECT log_id id,user_id userId,action,entity_type entityType,entity_id entityId,details,created_at createdAt FROM lf_activity_logs ORDER BY created_at DESC`)
    ]);
    this.data = { users: users.recordset, categories: categories.recordset, locations: locations.recordset, foundItems: found.recordset.map((row) => itemMap(row, 'found')), lostItems: lost.recordset.map((row) => itemMap(row, 'lost')), matches: matches.recordset, claims: claims.recordset.map((claim) => ({ ...claim, answers: Object.fromEntries(verification.recordset.filter((row) => row.claimId === claim.id).map((row) => [row.question, row.answer])) })), logs: logs.recordset };
  }
  async save() {}
  async authenticate(email, password) { const user = this.data.users.find((entry) => entry.email.toLowerCase() === String(email).toLowerCase() && entry.status === 'Active'); return user && await bcrypt.compare(password, user.passwordHash) ? this.userSafe(user) : null; }
  async categoryLocationIds(category, location) { const categoryRow = this.data.categories.find((row) => row.name === category); const locationRow = this.data.locations.find((row) => row.name === location); if (!categoryRow || !locationRow) throw Object.assign(new Error('Category or location is invalid'), { status: 422 }); return { categoryId: categoryRow.id, locationId: locationRow.id }; }
  async create(type, body, user, image) {
    const ids = await this.categoryLocationIds(body.category, body.location); const isFound = type === 'found';
    const request = bind(this.pool.request(), { ownerId: user.id, name: body.name, categoryId: ids.categoryId, color: body.color, brand: body.brand, locationId: ids.locationId, date: new Date(body.date), description: body.description, privateDetails: body.privateDetails, custody: body.custodyStatus || (user.role === 'USER' ? 'With Finder' : 'In Custody'), status: user.role === 'USER' ? (isFound ? 'Reported' : 'Open') : body.status || (isFound ? 'Unclaimed' : 'Open') });
    const result = await request.query(isFound ? `INSERT lf_found_items(reported_by_user_id,item_name,category_id,color,brand,found_location_id,found_date,description,private_details,custody_status,status) OUTPUT inserted.found_item_id id VALUES(@ownerId,@name,@categoryId,@color,@brand,@locationId,@date,@description,@privateDetails,@custody,@status)` : `INSERT lf_lost_items(user_id,item_name,category_id,color,brand,lost_location_id,lost_date,description,private_details,status) OUTPUT inserted.lost_item_id id VALUES(@ownerId,@name,@categoryId,@color,@brand,@locationId,@date,@description,@privateDetails,@status)`);
    const id = result.recordset[0].id; if (image) await bind(this.pool.request(), { type, id, path: `/uploads/${image.filename}`, original: image.originalname }).query(`INSERT lf_item_images(item_type,item_id,image_path,original_filename) VALUES(@type,@id,@path,@original)`);
    await this.reloadItems(); await this.recalculateSql(); await this.log(user.id, `${type}_item.create`, type, id); return this.get(type, id, user);
  }
  async reloadItems() {
    const fresh = new SqlStore(); fresh.pool = this.pool; await fresh.init();
    this.data.foundItems = fresh.data.foundItems; this.data.lostItems = fresh.data.lostItems; this.data.matches = fresh.data.matches; this.data.claims = fresh.data.claims; this.data.logs = fresh.data.logs;
  }
  async update(type, id, body, user) {
    const ids = await this.categoryLocationIds(body.category, body.location); const isFound = type === 'found';
    const request = bind(this.pool.request(), { id: Number(id), name: body.name, categoryId: ids.categoryId, color: body.color, brand: body.brand, locationId: ids.locationId, date: new Date(body.date), description: body.description, privateDetails: body.privateDetails, custody: body.custodyStatus, status: body.status });
    const result = await request.query(isFound ? `UPDATE lf_found_items SET item_name=@name,category_id=@categoryId,color=@color,brand=@brand,found_location_id=@locationId,found_date=@date,description=@description,private_details=COALESCE(@privateDetails,private_details),custody_status=COALESCE(@custody,custody_status),status=@status,updated_at=SYSUTCDATETIME() WHERE found_item_id=@id` : `UPDATE lf_lost_items SET item_name=@name,category_id=@categoryId,color=@color,brand=@brand,lost_location_id=@locationId,lost_date=@date,description=@description,private_details=COALESCE(@privateDetails,private_details),status=@status,updated_at=SYSUTCDATETIME() WHERE lost_item_id=@id`);
    if (!result.rowsAffected[0]) return null; await this.reloadItems(); await this.recalculateSql(); await this.log(user.id, `${type}_item.update`, type, Number(id)); return this.get(type, id, user);
  }
  async remove(type, id, user) {
    const isFound = type === 'found'; const request = bind(this.pool.request(), { id: Number(id), type });
    const result = await request.query(`DELETE lf_item_images WHERE item_type=@type AND item_id=@id; ${isFound ? 'DELETE lf_claim_verification WHERE claim_id IN (SELECT claim_id FROM lf_claims WHERE found_item_id=@id); DELETE lf_claims WHERE found_item_id=@id; DELETE lf_matches WHERE found_item_id=@id;' : 'DELETE lf_matches WHERE lost_item_id=@id;'} DELETE ${isFound ? 'lf_found_items' : 'lf_lost_items'} WHERE ${isFound ? 'found_item_id' : 'lost_item_id'}=@id`);
    if (!result.rowsAffected.at(-1)) return false; await this.reloadItems(); await this.recalculateSql(); await this.log(user.id, `${type}_item.delete`, type, Number(id)); return true;
  }
  async attachImages(type,id,files,user){for(const file of files)await bind(this.pool.request(),{type,id:Number(id),path:`/uploads/${file.filename}`,original:file.originalname}).query(`INSERT lf_item_images(item_type,item_id,image_path,original_filename) VALUES(@type,@id,@path,@original)`);await this.reloadItems();await this.log(user.id,`${type}_item.images`,type,Number(id));return files.map((file)=>`/uploads/${file.filename}`);}
  async recalculateSql() {
    const old = new Map(this.data.matches.map((match) => [match.id, match.status])); const calculated = buildMatches(this.data.lostItems, this.data.foundItems).map((match) => ({ ...match, status: old.get(match.id) || 'Pending' }));
    const transaction = new sql.Transaction(this.pool); await transaction.begin(); try { await new sql.Request(transaction).query('DELETE lf_matches'); for (const match of calculated) await bind(new sql.Request(transaction), match).query(`INSERT lf_matches(lost_item_id,found_item_id,match_score,category_score,color_score,location_score,date_score,brand_score,keyword_score,status) VALUES(@lostItemId,@foundItemId,@score,@category,@color,@location,@date,@brand,@keyword,@status)`); await transaction.commit(); this.data.matches = calculated; } catch (error) { await transaction.rollback(); throw error; }
  }
  async setMatch(id, status, user) { const match = this.data.matches.find((entry) => entry.id === id); if (!match) return null; await bind(this.pool.request(), { lostId: match.lostItemId, foundId: match.foundItemId, status }).query(`UPDATE lf_matches SET status=@status WHERE lost_item_id=@lostId AND found_item_id=@foundId`); match.status = status; await this.log(user.id, `match.${status.toLowerCase()}`, 'match', match.dbId || null); return match; }
  async createClaim(body, user) { const item=this.data.foundItems.find((entry)=>entry.id===Number(body.foundItemId));if(!item)throw Object.assign(new Error('Found item does not exist'),{status:404});if(['Claimed','Disposed'].includes(item.status))throw Object.assign(new Error('This item is no longer available to claim'),{status:409}); const duplicate = this.data.claims.some((claim) => claim.foundItemId === Number(body.foundItemId) && claim.claimantUserId === user.id && !['Rejected','Returned'].includes(claim.status)); if (duplicate) throw Object.assign(new Error('You already have an active claim for this item'), { status: 409 }); const result = await bind(this.pool.request(), { foundId: Number(body.foundItemId), userId: user.id }).query(`INSERT lf_claims(found_item_id,claimant_user_id) OUTPUT inserted.claim_id id VALUES(@foundId,@userId)`); const id=result.recordset[0].id; for(const [question,answer] of Object.entries(body.answers||{})) await bind(this.pool.request(),{id,question,answer}).query(`INSERT lf_claim_verification(claim_id,question,claimant_answer) VALUES(@id,@question,@answer)`); await bind(this.pool.request(),{foundId:Number(body.foundItemId)}).query(`UPDATE lf_found_items SET status='Claim Pending' WHERE found_item_id=@foundId`); await this.reloadItems(); await this.log(user.id,'claim.submit','claim',id); return this.data.claims.find((claim)=>claim.id===id); }
  async transitionClaim(id,status,user,reason) { const claim=this.data.claims.find((entry)=>entry.id===Number(id)); if(!claim)return null; const transaction=new sql.Transaction(this.pool);await transaction.begin();try{await bind(new sql.Request(transaction),{id:Number(id),status,userId:user.id,reason}).query(`UPDATE lf_claims SET status=@status,reviewed_by_user_id=@userId,reviewed_at=SYSUTCDATETIME(),rejection_reason=@reason WHERE claim_id=@id`); if(status==='Returned')await bind(new sql.Request(transaction),{foundId:claim.foundItemId}).query(`UPDATE lf_found_items SET status='Claimed',custody_status='Returned' WHERE found_item_id=@foundId; UPDATE lf_lost_items SET status='Resolved' WHERE lost_item_id IN (SELECT lost_item_id FROM lf_matches WHERE found_item_id=@foundId AND status='Confirmed')`); await transaction.commit();}catch(error){await transaction.rollback();throw error;}await this.reloadItems();await this.log(user.id,`claim.${status.toLowerCase()}`,'claim',Number(id));return this.data.claims.find((entry)=>entry.id===Number(id)); }
  async metaCreate(type,body,user){const singular=type==='categories'?'category':'location';const result=await bind(this.pool.request(),{name:body.name,description:body.description,status:body.status||'Active'}).query(`INSERT lf_${type}(name,description,status) OUTPUT inserted.${singular}_id id VALUES(@name,@description,@status)`);const row={id:result.recordset[0].id,...body,status:body.status||'Active'};this.data[type].push(row);await this.log(user.id,`${type}.create`,type,row.id);return row;}
  async metaUpdate(type,id,body,user){const singular=type==='categories'?'category':'location';const result=await bind(this.pool.request(),{id:Number(id),name:body.name,description:body.description,status:body.status}).query(`UPDATE lf_${type} SET name=@name,description=@description,status=@status WHERE ${singular}_id=@id`);if(!result.rowsAffected[0])return null;const row=this.data[type].find((entry)=>entry.id===Number(id));Object.assign(row,body);await this.log(user.id,`${type}.update`,type,Number(id));return row;}
  async addUser(body){const hash=await bcrypt.hash(body.password,10);const result=await bind(this.pool.request(),{first:body.firstName,last:body.lastName,email:body.email,hash,role:body.role||'USER'}).query(`INSERT lf_users(first_name,last_name,email,password_hash,role_id) OUTPUT inserted.user_id id VALUES(@first,@last,@email,@hash,(SELECT role_id FROM lf_roles WHERE role_name=@role))`);const user={id:result.recordset[0].id,firstName:body.firstName,lastName:body.lastName,email:body.email,passwordHash:hash,role:body.role||'USER',status:'Active'};this.data.users.push(user);return this.userSafe(user);}
  async updateUser(id,body){const user=this.data.users.find((entry)=>entry.id===Number(id));if(!user)return null;const hash=body.password?await bcrypt.hash(body.password,10):user.passwordHash;await bind(this.pool.request(),{id:Number(id),first:body.firstName??user.firstName,last:body.lastName??user.lastName,email:body.email??user.email,hash,role:body.role??user.role,status:body.status??user.status}).query(`UPDATE lf_users SET first_name=@first,last_name=@last,email=@email,password_hash=@hash,role_id=(SELECT role_id FROM lf_roles WHERE role_name=@role),status=@status,updated_at=SYSUTCDATETIME() WHERE user_id=@id`);const{password,...changes}=body;Object.assign(user,changes,{passwordHash:hash});return this.userSafe(user);}
  async disableUser(id){const result=await bind(this.pool.request(),{id:Number(id)}).query(`UPDATE lf_users SET status='Inactive',updated_at=SYSUTCDATETIME() WHERE user_id=@id`);const user=this.data.users.find((entry)=>entry.id===Number(id));if(user)user.status='Inactive';return Boolean(result.rowsAffected[0]);}
  async metaDelete(type,id,user){const singular=type==='categories'?'category':'location';try{const result=await bind(this.pool.request(),{id:Number(id)}).query(`DELETE lf_${type} WHERE ${singular}_id=@id`);if(!result.rowsAffected[0])return false;this.data[type]=this.data[type].filter((entry)=>entry.id!==Number(id));await this.log(user.id,`${type}.delete`,type,Number(id));return true;}catch(error){if(error.number===547)throw Object.assign(new Error(`Cannot delete a ${singular} that is used by item reports`),{status:409});throw error;}}
  async log(userId,action,entityType,entityId,details=''){const result=await bind(this.pool.request(),{userId,action,entityType,entityId,details}).query(`INSERT lf_activity_logs(user_id,action,entity_type,entity_id,details) OUTPUT inserted.log_id id,inserted.created_at createdAt VALUES(@userId,@action,@entityType,@entityId,@details)`);this.data.logs.unshift({id:result.recordset[0].id,userId,action,entityType,entityId,details,createdAt:result.recordset[0].createdAt});}
}
